### ISSUE TITLE
inference on custom dataset-images

### ISSUE THREAD

**Issue by caprone** [pranaysingh25/Automatic-Image-Captioning#2]
HI
but for only inference I also need to load --coco dataset --???

thanks

**Comment by pranaysingh25** [comment]
For inference, you just need the weights, i.e. you need to load the trained model that I have provided. For testing it on one of your images, you need to provide that image as input to saved model.
If you have any queries regarding working or project experience, you can hit me up on linkedin instead.
www.linkedin.com/in/pranaysingh25

However, If you think there is some issue with the project, you are definately encouraged to raise the issue here instead.
