### ISSUE TITLE
ModuleNotFoundError when try load 'vocab' file

### ISSUE THREAD

**Issue by caprone** [pranaysingh25/Automatic-Image-Captioning#3]
HI
when I try to load 'vocabulary.pkl' file : ModuleNotFoundError: No module named 'vocabulary' occurs;
probably when You created the pickle file, ther're references to that module inside pickle object;
also if I import vocabulary module or add it to sys path, the issue remains...
then I must create vocabulary from scratch?
i can't use your model for test on different dataset images..

thanks again

**Comment by pranaysingh25** [comment]
you have to load already created "vocab.pkl" file, if you wanna create your own vocabulary file you can create it. If you're using windows you should be having all the dependencies before in your system since it is a well known fact that using COCO dataset on windows comes with a lot of pain. You might run into ModuleNotFoundError like "No module named 'pycocotools' ". But if you do a little research on stackoverflow you can debug it to know what files/modules are missing in your environment. If you have all the dependencies, its your choice to either use my vocab.pkl file or create your own. Creating new takes time if your not using GPU

**Comment by caprone** [comment]
a ok, no problem, I didn't think it was necessary to install pycocotools also for testing,  it's not worth it...
thanks anyway
